# This workflow
# - does a clean install of node dependencies
# - builds the source code
# - runs tests across different versions of node and operating systems

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# each job executes in a fresh instance of the virtual environment
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: npm install and build
      run: |
        npm install
        npm run build --if-present
  
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2016]
        node-version: [12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
        npm test
      env:
        CI: true
